Update travis.yaml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,4 +1,4 @@
-# Travis-CI Build for OpenRA/ra2
+# Travis-CI Build for OpenRAModSDK
 # see travis-ci.org for details
 
 language: csharp
@@ -9,35 +9,19 @@ addons:
   apt:
     packages:
     - liblua5.1-0
-    - p7zip-full
     - nsis
     - nsis-common
 
 script:
  - make
  - . mod.config;
+   awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (CR, not CRLF) line endings.\n"; travis_terminate 1);
    if [ "${TRAVIS_TEST_MOD}" == "True" ]; then make test || travis_terminate 1; fi;
-   if [ "${TRAVIS_TEST_PACKAGING}" == "True" ]; then ./packaging/package-all.sh test-0 || travis_terminate 1; fi
-# Crashes, see https://github.com/OpenRA/OpenRA/issues/14013
-# - make check
-
-branches:
-  only:
-    - master
-
-# Notify developers when build passed/failed.
-notifications:
-  irc:
-    template:
-      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
-    channels:
-      - "irc.freenode.net#openra"
-    use_notice: true
-    skip_join: true
+   if [ "${TRAVIS_TEST_PACKAGING}" == "True" ]; then make check-packaging-scripts && ./packaging/package-all.sh test-0 || travis_terminate 1; fi
 
 before_deploy:
  - mkdir build
- - cd build && ../packaging/package-all.sh ${TRAVIS_TAG} ${PWD} && cd ..
+ - make check-packaging-scripts && cd build && ../packaging/package-all.sh ${TRAVIS_TAG} ${PWD} && cd ..
  - . mod.config
 
 deploy:
