another test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,6 @@ name: Continuous Integration
 on:
   push:
   pull_request:
-    branches: [ bleed, 'prep-*' ]
 
 permissions:
   contents: read  #  to fetch code (actions/checkout)
@@ -14,9 +13,6 @@ jobs:
     runs-on: ubuntu-22.04
 
     steps:
-      - name: Remove System .NET
-        run: sudo apt-get remove -y dotnet*
-
       - name: Clone Repository
         uses: actions/checkout@v4
 
@@ -25,16 +21,21 @@ jobs:
         with:
           dotnet-version: '6.0.x'
 
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+
       - name: Check Code
         run: |
           make check
-          make tests
+          make check-packaging-scripts
 
-      - name: Check Mods
+      - name: Check Mod
         run: |
           sudo apt-get install lua5.1
           make check-scripts
-          make TREAT_WARNINGS_AS_ERRORS=true test
+          make test
 
   linux-mono:
     name: Linux (mono)
@@ -44,15 +45,21 @@ jobs:
       - name: Clone Repository
         uses: actions/checkout@v4
 
+      - name: Prepare Environment
+        run: |
+          . mod.config;
+          awk '/\r$$/ { exit(1); }' mod.config || (printf "Invalid mod.config format. File must be saved using unix-style (LF, not CRLF or CR) line endings.\n"; exit 1);
+
       - name: Check Code
         run: |
+          # check-packaging-scripts does not depend on .net/mono, so is not needed here
           mono --version
           make RUNTIME=mono check
 
-      - name: Check Mods
+      - name: Check Mod
         run: |
           # check-scripts does not depend on .net/mono, so is not needed here
-          make RUNTIME=mono TREAT_WARNINGS_AS_ERRORS=true test
+          make RUNTIME=mono test
 
   windows:
     name: Windows (.NET 6.0)
@@ -73,12 +80,10 @@ jobs:
           # Work around runtime failures on the GH Actions runner
           dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
           .\make.ps1 check
-          .\make.ps1 tests
 
       - name: Check Mods
         run: |
           choco install lua --version 5.1.5.52
           $ENV:Path = $ENV:Path + ";C:\Program Files (x86)\Lua\5.1\"
-          $ENV:TREAT_WARNINGS_AS_ERRORS = "true"
           .\make.ps1 check-scripts
           .\make.ps1 test
